[phases.install]
cmds = ["cd booking-scraper-service && npm install --include=dev"]

[phases.build]
cmds = ["cd booking-scraper-service && npx tsc -p ."]

[start]
cmd = "PORT=8080 node booking-scraper-service/dist/index.js"

[variables]
PORT = "8080"
